/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations['health_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/reviews': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Review
     * @description Accept a bounded request without persisting or logging source code.
     */
    post: operations['create_review_v1_reviews_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * Finding
     * @description An advisory issue anchored to changed lines.
     */
    Finding: {
      /**
       * Severity
       * @enum {string}
       */
      severity: 'P0' | 'P1' | 'P2';
      /** Path */
      path: string;
      /** Start Line */
      start_line: number;
      /** End Line */
      end_line: number;
      /** Title */
      title: string;
      /** Evidence */
      evidence: string;
      /** Recommendation */
      recommendation: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /**
     * RequestedContext
     * @description A single file explicitly requested by the reviewer.
     */
    RequestedContext: {
      /**
       * Path
       * @description 仓库相对路径
       */
      path: string;
      /**
       * Content
       * @description 已脱敏的文件内容
       */
      content: string;
    };
    /**
     * ReviewRequest
     * @description The complete v1 review input: a diff and bounded optional context.
     */
    ReviewRequest: {
      /** Organization Id */
      organization_id: string;
      /** Diff */
      diff: string;
      /** Context */
      context?: components['schemas']['RequestedContext'][];
    };
    /** ReviewResponse */
    ReviewResponse: {
      /** Review Id */
      review_id: string;
      /**
       * Status
       * @enum {string}
       */
      status: 'completed' | 'needs_context';
      /** Report */
      report: string;
      /** Findings */
      findings?: components['schemas']['Finding'][];
      /** Requested Context Paths */
      requested_context_paths?: string[];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
    };
  };
  create_review_v1_reviews_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReviewRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReviewResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
